### ISSUE TITLE
build_ngtf.py fails on the activation of venv-tf-py3

### ISSUE THREAD

**Issue by samolisov** [NervanaSystems/ngraph-tf#391]
The `build_ngtf.py` script fails about after the start:

```bash
> python3 ./build_ngtf.py
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/python3
Also creating executable in /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/python
Installing setuptools, pip, wheel...
done.
Loading virtual environment from: /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3
Traceback (most recent call last):
  File "./build_ngtf.py", line 534, in <module>
    main()
  File "./build_ngtf.py", line 447, in main
    load_venv(venv_dir)
  File "./build_ngtf.py", line 107, in load_venv
    dict(__file__=activate_this_file), dict(__file__=activate_this_file))
  File "/home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/activate_this.py", line 46, in <module>
    sys.path[:] = [i for i in new if i not in prev] + [i for i in new if i in prev]
  File "/home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/activate_this.py", line 46, in <listcomp>
    sys.path[:] = [i for i in new if i not in prev] + [i for i in new if i in prev]
NameError: name 'prev' is not defined
```
It looks like a problem in the virtualenv activation script but I can run `python3 ./build/venv-tf-py3/bin/activate_this.py` without any problems.

I use the latest version of **virtualenv**: 16.2.0.
Version of **python**: 3.6.5

---

P.S. If the `build_ngtf.py` is started under **python 2**, not **python 3**, the activation works fine:

```bash
> python ./build_ngtf.py
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/python3
Also creating executable in /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/python
Installing setuptools, pip, wheel...
done.
Loading virtual environment from: /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3
Loading virtual environment from: /home/pavel/ngraph/ngraph-tf/build/venv-tf-py3
PIP location
/home/pavel/ngraph/ngraph-tf/build/venv-tf-py3/bin/pip
Requirement already up-to-date: pip in ./venv-tf-py3/lib/python3.6/site-packages (18.1)
Requirement already up-to-date: setuptools in ./venv-tf-py3/lib/python3.6/site-packages (40.6.3)
Collecting psutil
...
```

but the mix of **python 3** and **python 2** will be used during the rest of the script, for example, **tensorflow** will be configured with `PYTHON_LIB_PATH` pointing to `build/venv-tf-py3/lib/python2.7/site-packages` and of course will fail during the build.

**Comment by cepera** [comment]
I have the same issue with Python 3.5.4

**Comment by cepera** [comment]
hi, maybe it is because of last version of virtualenv. 
I was able to workaround the problem by removing *compile* from *load_venv* in _build_ngtf.py_:


```
$ git diff
diff --git a/build_ngtf.py b/build_ngtf.py
index 125391c..8c59718 100755
--- a/build_ngtf.py
+++ b/build_ngtf.py
@@ -102,9 +102,8 @@ def load_venv(venv_dir):
     # obscure system without Python 3
     # execfile(activate_this_file, dict(__file__=activate_this_file))
     exec(
-        compile(
-            open(activate_this_file, "rb").read(), activate_this_file, 'exec'),
-        dict(__file__=activate_this_file), dict(__file__=activate_this_file))
+            open(activate_this_file, "rb").read(),
+        dict(__file__=activate_this_file))

     return venv_dir
```

**Comment by samolisov** [comment]
@серега

I've checked on `virtualenv 16.1.0` - everything is working fine, I believe 16.2.0 is a root of the problem.

**Comment by avijit-nervana** [comment]
Thanks folks for reporting this. The solution you guys came up with is correct - virtualenv 16.2.0 won't work as you fund out. We will update the document.
