### ISSUE TITLE
pip install and run show an error "undefined symbol: _ZNK10tensorflow4Node11type_stringEv"

### ISSUE THREAD

**Issue by jaebaek** [NervanaSystems/ngraph-tf#532]
After installing tensorflow and ngraph-tf, executing `python -c "import tensorflow as tf; print('TensorFlow version: ',tf.__version__);import ngraph_bridge; print(ngraph_bridge.__version__)"` showed the following error:

```
➜  ~ source tf-test/bin/activate
(tf-test) ➜  ~  pip install -U tensorflow 
Requirement already up-to-date: tensorflow in ./tf-test/lib/python3.7/site-packages (1.13.1)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (0.33.1)
Requirement already satisfied, skipping upgrade: absl-py>=0.1.6 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (0.7.1)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (0.7.1)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in ./anaconda3/envs/plaidml/lib/python3.7/site-packages (from tensorflow) (1.16.3)
Requirement already satisfied, skipping upgrade: tensorboard<1.14.0,>=1.13.0 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (1.13.1)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (1.0.7)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (1.20.0)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<1.14.0rc0,>=1.13.0 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (1.13.0)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (0.2.2)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (1.0.9)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.1 in ./tf-test/lib/python3.7/site-packages (from tensorflow) (3.7.1)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in ./anaconda3/envs/plaidml/lib/python3.7/site-packages (from tensorflow) (1.12.0)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in ./tf-test/lib/python3.7/site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow) (0.15.2)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in ./tf-test/lib/python3.7/site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow) (3.1)
Requirement already satisfied, skipping upgrade: h5py in ./tf-test/lib/python3.7/site-packages (from keras-applications>=1.0.6->tensorflow) (2.9.0)
Requirement already satisfied, skipping upgrade: mock>=2.0.0 in ./tf-test/lib/python3.7/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow) (2.0.0)
Requirement already satisfied, skipping upgrade: setuptools in ./tf-test/lib/python3.7/site-packages (from protobuf>=3.6.1->tensorflow) (41.0.1)
Requirement already satisfied, skipping upgrade: pbr>=0.11 in ./tf-test/lib/python3.7/site-packages (from mock>=2.0.0->tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow) (5.1.3)
(tf-test) ➜  ~  pip install -U ngraph-tensorflow-bridge
Requirement already up-to-date: ngraph-tensorflow-bridge in ./tf-test/lib/python3.7/site-packages (0.12.0)
(tf-test) ➜  ~  python -c "import tensorflow as tf; print('TensorFlow version: ',tf.__version__);import ngraph_bridge; print(ngraph_bridge.__version__)"
TensorFlow version:  1.13.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jaebaek/tf-test/lib/python3.7/site-packages/ngraph_bridge/__init__.py", line 94, in <module>
    os.path.join(libpath, 'libngraph_bridge.' + ext))
  File "/home/jaebaek/anaconda3/envs/plaidml/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/jaebaek/anaconda3/envs/plaidml/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jaebaek/tf-test/lib/python3.7/site-packages/ngraph_bridge/libngraph_bridge.so: undefined symbol: _ZNK10tensorflow4Node11type_stringEv
(tf-test) ➜  ~ 
```

**Comment by hailijuan** [comment]
I also met with the similar failure. Any suggestions would be appreciated.

**Comment by SleepProgger** [comment]
Can't help with that issue, but you are posting on the wrong repository.
This project moved to https://github.com/tensorflow/ngraph-bridge
