### ISSUE TITLE
Building from source code shows an error

### ISSUE THREAD

**Issue by jaebaek** [NervanaSystems/ngraph-tf#533]
I followed the instruction [here](https://github.com/NervanaSystems/ngraph-tf#option-2-build-ngraph-bridge-from-source).

```
➜  ngraph-tf git:(master) ✗ python3.5 build_ngtf.py
ARTIFACTS location: /home/jaebaek/ngraph-tf/build_cmake/artifacts
Running virtualenv with interpreter /home/jaebaek/anaconda3/bin/python3
Using base prefix '/home/jaebaek/anaconda3'
Overwriting /home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3/lib/python3.7/orig-prefix.txt with new content
New python executable in /home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3/bin/python3
Not overwriting existing python script /home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3/bin/python (you must use /home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3/bin/python3)
Installing setuptools, pip, wheel...
done.
Loading virtual environment from: /home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3
Traceback (most recent call last):
  File "build_ngtf.py", line 314, in <module>
    main()
  File "build_ngtf.py", line 141, in main
    load_venv(venv_dir)
  File "/home/jaebaek/ngraph-tf/tools/build_utils.py", line 110, in load_venv
    dict(__file__=activate_this_file), dict(__file__=activate_this_file))
  File "/home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3/bin/activate_this.py", line 46, in <module>
    sys.path[:] = [i for i in new if i not in prev] + [i for i in new if i in prev]
  File "/home/jaebaek/ngraph-tf/build_cmake/venv-tf-py3/bin/activate_this.py", line 46, in <listcomp>
    sys.path[:] = [i for i in new if i not in prev] + [i for i in new if i in prev]
NameError: name 'prev' is not defined
```

**Comment by avijit-nervana** [comment]
This is related to the version of the virtualenv installed on your system. The version needs to be 1.16.0 or less. Please let us know if you still have issues
